### ISSUE TITLE
Create fixtures for all project models

### ISSUE THREAD

**Issue by brylie** [WesternFriend/westernfriend.org#776]
It would be helpful to provide data fixtures so we can easily set up a development environment.

## Task
- [ ] determine how best to set up Django fixtures
- [ ] scaffold initial site content with `scaffold_initial_content` management command
- [ ] create additional model data - at least 2-10 of each leaf node
- [ ] consider using Django factory_boy since it is included in the project to dynamically generate the fixtures
